const icon = require('../assets/img/servicos/solar.png');

export const services = [
  {
    id: 1,
    value: 1,
    label: 'Curativo de lesões',
    texto: 'Curativo de lesões',
    price: '400,00',
    image: icon,
  },
  {
    id: 2,
    value: 2,
    label: 'Curativo de cateter',
    texto: 'Curativo de cateter',
    price: '300,00',
    image: icon,
  },
  {
    id: 3,
    value: 3,
    label: 'Banho',
    texto: 'Banho',
    price: '250,00',
    image: icon,
  },
  {
    id: 4,
    value: 4,
    label: 'Administração de Medicamento',
    texto: 'Administração de Medicamento',
    price: '1200,00',
    image: icon,
  },
  {
    id: 5,
    value: 5,
    label: 'Orientação sobre sondas',
    texto: 'Orientação sobre sondas',
    price: '200,00',
    image: icon,
  },
  {
    id: 6,
    value: 6,
    label: 'Administração de dieta enteral',
    texto: 'Administração de dieta enteral',
    price: '300,00',
    image: icon,
  },
  {
    id: 7,
    value: 7,
    label: 'Vacina',
    texto: 'Vacina',
    price: '300,00',
    image: icon,
  },
  {
    id: 8,
    value: 8,
    label: 'Passagem de sonda de alívio',
    texto: 'Passagem de sonda de alívio',
    price: '500,00',
    image: icon,
  },
  {
    id: 9,
    value: 9,
    label: 'Passagem de sonda vesical de demora',
    texto: 'Passagem de sonda vesical de demora',
    price: '1000,00',
    image: icon,
  },
  {
    id: 10,
    value: 10,
    label: 'Vacina',
    texto: 'Vacina',
    price: '300,00',
    image: icon,
  },
  {
    id: 11,
    value: 11,
    label: 'Passagem de sonda de alívio',
    texto: 'Passagem de sonda de alívio',
    price: '500,00',
    image: icon,
  },
  {
    id: 12,
    value: 12,
    label: 'Passagem de sonda vesical de demora',
    texto: 'Passagem de sonda vesical de demora',
    price: '1000,00',
    image: icon,
  },
];
